<?php

use Illuminate\Database\Seeder;
use App\Models\XCountries;

class XCountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
		  [
			'country_code' => 'AF',
			'name' => 'Afghanistan',
			'continent' => 'Asia',
			'offset' => '4.5',
			'TimeZoneId' => 'Asia/Kabul',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'AL',
			'name' => 'Albania',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Tirane',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'DZ',
			'name' => 'Algeria',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Algiers',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'AD',
			'name' => 'Andorra',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Andorra',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'AO',
			'name' => 'Angola',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Luanda',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'AG',
			'name' => 'Antigua and Barbuda',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Antigua',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'AR',
			'name' => 'Argentina',
			'continent' => 'Americas',
			'offset' => '-3',
			'TimeZoneId' => 'America/Argentina/Buenos_Aires',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'AM',
			'name' => 'Armenia',
			'continent' => 'Asia',
			'offset' => '4',
			'TimeZoneId' => 'Asia/Yerevan',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'AU',
			'name' => 'Australia',
			'continent' => 'Oceania',
			'offset' => '8',
			'TimeZoneId' => 'Australia/Sydney',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'AT',
			'name' => 'Austria',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Vienna',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'AZ',
			'name' => 'Azerbaijan',
			'continent' => 'Asia',
			'offset' => '4',
			'TimeZoneId' => 'Asia/Baku',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BS',
			'name' => 'Bahamas',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Nassau',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'BH',
			'name' => 'Bahrain',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Bahrain',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'BD',
			'name' => 'Bangladesh',
			'continent' => 'Asia',
			'offset' => '6',
			'TimeZoneId' => 'Asia/Dhaka',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'BB',
			'name' => 'Barbados',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Barbados',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BY',
			'name' => 'Belarus',
			'continent' => 'Europe',
			'offset' => '3',
			'TimeZoneId' => 'Europe/Minsk',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BE',
			'name' => 'Belgium',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Brussels',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'BZ',
			'name' => 'Belize',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/Belize',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BJ',
			'name' => 'Benin',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Porto-Novo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BT',
			'name' => 'Bhutan',
			'continent' => 'Asia',
			'offset' => '6',
			'TimeZoneId' => 'Asia/Thimphu',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BO',
			'name' => 'Bolivia',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/La_Paz',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BA',
			'name' => 'Bosnia and Herzegovina',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Sarajevo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BW',
			'name' => 'Botswana',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Gaborone',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BR',
			'name' => 'Brazil',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Sao_Paulo',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'BN',
			'name' => 'Brunei',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Brunei',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BG',
			'name' => 'Bulgaria',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Sofia',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'BF',
			'name' => 'Burkina Faso',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Ouagadougou',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'BI',
			'name' => 'Burundi',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Bujumbura',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'KH',
			'name' => 'Cambodia',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Phnom_Penh',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CM',
			'name' => 'Cameroon',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Douala',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'CA',
			'name' => 'Canada',
			'continent' => 'Americas',
			'offset' => '-8',
			'TimeZoneId' => 'America/Toronto',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'CV',
			'name' => 'Cape Verde',
			'continent' => 'Africa',
			'offset' => '-1',
			'TimeZoneId' => 'Atlantic/Cape_Verde',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CF',
			'name' => 'Central African Republic',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Bangui',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TD',
			'name' => 'Chad',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Ndjamena',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CL',
			'name' => 'Chile',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Santiago',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'CN',
			'name' => 'China',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Shanghai',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'CO',
			'name' => 'Colombia',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Bogota',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'KM',
			'name' => 'Comoros',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Indian/Comoro',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CG',
			'name' => 'Congo - Brazzaville',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Brazzaville',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CD',
			'name' => 'Congo - Kinshasa',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Kinshasa',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CR',
			'name' => 'Costa Rica',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/Costa_Rica',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'CI',
			'name' => 'Côte d\'Ivoire',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Abidjan',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'HR',
			'name' => 'Croatia',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Zagreb',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'CY',
			'name' => 'Cyprus',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Asia/Nicosia',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'CZ',
			'name' => 'Czech Republic',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Prague',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'DK',
			'name' => 'Denmark',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Copenhagen',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'DJ',
			'name' => 'Djibouti',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Djibouti',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'DM',
			'name' => 'Dominica',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Dominica',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'DO',
			'name' => 'Dominican Republic',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Santo_Domingo',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'EC',
			'name' => 'Ecuador',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'Pacific/Galapagos',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'EG',
			'name' => 'Egypt',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Cairo',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'SV',
			'name' => 'El Salvador',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/El_Salvador',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'GQ',
			'name' => 'Equatorial Guinea',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Malabo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ER',
			'name' => 'Eritrea',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Asmara',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'EE',
			'name' => 'Estonia',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Tallinn',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'ET',
			'name' => 'Ethiopia',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Addis_Ababa',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'FJ',
			'name' => 'Fiji',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Fiji',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'FI',
			'name' => 'Finland',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Helsinki',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'FR',
			'name' => 'France',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Paris',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'GA',
			'name' => 'Gabon',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Libreville',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GM',
			'name' => 'Gambia',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Banjul',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GE',
			'name' => 'Georgia',
			'continent' => 'Asia',
			'offset' => '4',
			'TimeZoneId' => 'Asia/Tbilisi',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'DE',
			'name' => 'Germany',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Berlin',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'GH',
			'name' => 'Ghana',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Accra',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'GR',
			'name' => 'Greece',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Athens',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'GD',
			'name' => 'Grenada',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Grenada',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GT',
			'name' => 'Guatemala',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/Guatemala',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GN',
			'name' => 'Guinea',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Conakry',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GW',
			'name' => 'Guinea-Bissau',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Bissau',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'GY',
			'name' => 'Guyana',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Guyana',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'HT',
			'name' => 'Haiti',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Port-au-Prince',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'HN',
			'name' => 'Honduras',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/Tegucigalpa',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'HU',
			'name' => 'Hungary',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Budapest',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'IS',
			'name' => 'Iceland',
			'continent' => 'Europe',
			'offset' => '0',
			'TimeZoneId' => 'Atlantic/Reykjavik',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'IN',
			'name' => 'India',
			'continent' => 'Asia',
			'offset' => '5.5',
			'TimeZoneId' => 'Asia/Kolkata',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ID',
			'name' => 'Indonesia',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Jakarta',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'IQ',
			'name' => 'Iraq',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Baghdad',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'IE',
			'name' => 'Ireland',
			'continent' => 'Europe',
			'offset' => '0',
			'TimeZoneId' => 'Europe/Dublin',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'IL',
			'name' => 'Israel',
			'continent' => 'Asia',
			'offset' => '2',
			'TimeZoneId' => 'Asia/Jerusalem',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'IT',
			'name' => 'Italy',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Rome',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'JM',
			'name' => 'Jamaica',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Jamaica',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'JP',
			'name' => 'Japan',
			'continent' => 'Asia',
			'offset' => '9',
			'TimeZoneId' => 'Asia/Tokyo',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'JO',
			'name' => 'Jordan',
			'continent' => 'Asia',
			'offset' => '2',
			'TimeZoneId' => 'Asia/Amman',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'KZ',
			'name' => 'Kazakhstan',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Asia/Almaty',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'KE',
			'name' => 'Kenya',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Nairobi',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'KI',
			'name' => 'Kiribati',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Tarawa',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'KW',
			'name' => 'Kuwait',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Kuwait',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'KG',
			'name' => 'Kyrgyzstan',
			'continent' => 'Asia',
			'offset' => '6',
			'TimeZoneId' => 'Asia/Bishkek',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LA',
			'name' => 'Laos',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Vientiane',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LV',
			'name' => 'Latvia',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Riga',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'LB',
			'name' => 'Lebanon',
			'continent' => 'Asia',
			'offset' => '2',
			'TimeZoneId' => 'Asia/Beirut',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'LS',
			'name' => 'Lesotho',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Maiu',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LR',
			'name' => 'Liberia',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Monrovia',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LY',
			'name' => 'Libya',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Tripoli',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LI',
			'name' => 'Liechtenstein',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Vaduz',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LT',
			'name' => 'Lithuania',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Vilnius',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'LU',
			'name' => 'Luxembourg',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Luxembourg',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'MK',
			'name' => 'Macedonia (FYROM)',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Skopje',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MG',
			'name' => 'Madagascar',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Indian/Antananarivo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MW',
			'name' => 'Malawi',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Blantyre',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MY',
			'name' => 'Malaysia',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Kuala_Lumpur',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'MV',
			'name' => 'Maldives',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Indian/Maldives',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'ML',
			'name' => 'Mali',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Bamako',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MT',
			'name' => 'Malta',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Malta',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'MH',
			'name' => 'Marshall Islands',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Majuro',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MR',
			'name' => 'Mauritania',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Nouakchott',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MU',
			'name' => 'Mauritius',
			'continent' => 'Africa',
			'offset' => '4',
			'TimeZoneId' => 'Indian/Mauritius',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'MX',
			'name' => 'Mexico',
			'continent' => 'Americas',
			'offset' => '-8',
			'TimeZoneId' => 'America/Mexico_City',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'FM',
			'name' => 'Micronesia',
			'continent' => 'Oceania',
			'offset' => '10',
			'TimeZoneId' => 'Pacific/Pohnpei',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MD',
			'name' => 'Moldova',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Chisinau',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MC',
			'name' => 'Monaco',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Monaco',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MN',
			'name' => 'Mongolia',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Ulaanbaatar',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ME',
			'name' => 'Montenegro',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Podgorica',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MA',
			'name' => 'Morocco',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Casablanca',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'MZ',
			'name' => 'Mozambique',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Maputo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'MM',
			'name' => 'Myanmar [Burma]',
			'continent' => 'Asia',
			'offset' => '6.5',
			'TimeZoneId' => 'Asia/Yangon',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'NA',
			'name' => 'Namibia',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Windhoek',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'NR',
			'name' => 'Nauru',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Nauru',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'NP',
			'name' => 'Nepal',
			'continent' => 'Asia',
			'offset' => '5.8',
			'TimeZoneId' => 'Asia/Kathmandu',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'NL',
			'name' => 'Netherlands',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Amsterdam',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'NZ',
			'name' => 'New Zealand',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Auckland',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'NI',
			'name' => 'Nicaragua',
			'continent' => 'Americas',
			'offset' => '-6',
			'TimeZoneId' => 'America/Managua',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'NE',
			'name' => 'Niger',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Niamey',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'NG',
			'name' => 'Nigeria',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Lagos',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'NO',
			'name' => 'Norway',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Oslo',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'OM',
			'name' => 'Oman',
			'continent' => 'Asia',
			'offset' => '4',
			'TimeZoneId' => 'Asia/Muscat',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'PK',
			'name' => 'Pakistan',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Asia/Karachi',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'PW',
			'name' => 'Palau',
			'continent' => 'Oceania',
			'offset' => '9',
			'TimeZoneId' => 'Pacific/Palau',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'PS',
			'name' => 'Palestine',
			'continent' => 'Asia',
			'offset' => '2',
			'TimeZoneId' => 'Asia/Gaza',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'PA',
			'name' => 'Panama',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Panama',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'PG',
			'name' => 'Papua New Guinea',
			'continent' => 'Oceania',
			'offset' => '10',
			'TimeZoneId' => 'Pacific/Port_Moresby',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'PY',
			'name' => 'Paraguay',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Asuncion',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'PE',
			'name' => 'Peru',
			'continent' => 'Americas',
			'offset' => '-5',
			'TimeZoneId' => 'America/Lima',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'PH',
			'name' => 'Philippines',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Manila',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'PL',
			'name' => 'Poland',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Warsaw',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'PT',
			'name' => 'Portugal',
			'continent' => 'Europe',
			'offset' => '0',
			'TimeZoneId' => 'Europe/Lisbon',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'QA',
			'name' => 'Qatar',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Qatar',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'RO',
			'name' => 'Romania',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Bucharest',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'RU',
			'name' => 'Russia',
			'continent' => 'Europe',
			'offset' => '3',
			'TimeZoneId' => 'Europe/Moscow',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'RW',
			'name' => 'Rwanda',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Kigali',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'KN',
			'name' => 'Saint Kitts and Nevis',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/St_Kitts',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'LC',
			'name' => 'Saint Lucia',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/St_Lucia',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'VC',
			'name' => 'Saint Vincent and the Grenadines',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/St_Vincent',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'WS',
			'name' => 'Samoa',
			'continent' => 'Oceania',
			'offset' => '13',
			'TimeZoneId' => 'Pacific/Apia',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SM',
			'name' => 'San Marino',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/San_Marino',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ST',
			'name' => 'São Tomé and Príncipe',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Sao_Tome',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SA',
			'name' => 'Saudi Arabia',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Riyadh',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'SN',
			'name' => 'Senegal',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Dakar',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'RS',
			'name' => 'Serbia',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Belgrade',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SC',
			'name' => 'Seychelles',
			'continent' => 'Africa',
			'offset' => '4',
			'TimeZoneId' => 'Indian/Mahe',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SL',
			'name' => 'Sierra Leone',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Freetown',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SG',
			'name' => 'Singapore',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Singapore',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'SK',
			'name' => 'Slovakia',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Bratislava',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'SI',
			'name' => 'Slovenia',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Ljubljana',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'SB',
			'name' => 'Solomon Islands',
			'continent' => 'Oceania',
			'offset' => '11',
			'TimeZoneId' => 'Pacific/Guadalcanal',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SO',
			'name' => 'Somalia',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Mogadishu',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ZA',
			'name' => 'South Africa',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Johannesburg',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'KR',
			'name' => 'South Korea',
			'continent' => 'Asia',
			'offset' => '9',
			'TimeZoneId' => 'Asia/Seoul',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'ES',
			'name' => 'Spain',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Madrid',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'LK',
			'name' => 'Sri Lanka',
			'continent' => 'Asia',
			'offset' => '5.5',
			'TimeZoneId' => 'Asia/Colombo',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'SR',
			'name' => 'Suriname',
			'continent' => 'Americas',
			'offset' => '-3',
			'TimeZoneId' => 'America/Paramaribo',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SZ',
			'name' => 'Swaziland',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Mbabane',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'SE',
			'name' => 'Sweden',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Stockholm',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'CH',
			'name' => 'Switzerland',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Zurich',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'TW',
			'name' => 'Taiwan',
			'continent' => 'Asia',
			'offset' => '8',
			'TimeZoneId' => 'Asia/Taipei',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'TJ',
			'name' => 'Tajikistan',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Asia/Dushanbe',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TZ',
			'name' => 'Tanzania',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Dar_es_Salaam',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TH',
			'name' => 'Thailand',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Bangkok',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'TL',
			'name' => 'Timor-Leste',
			'continent' => 'Asia',
			'offset' => '9',
			'TimeZoneId' => 'Asia/Dili',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TG',
			'name' => 'Togo',
			'continent' => 'Africa',
			'offset' => '0',
			'TimeZoneId' => 'Africa/Lome',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TO',
			'name' => 'Tonga',
			'continent' => 'Oceania',
			'offset' => '13',
			'TimeZoneId' => 'Pacific/Tongatapu',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TT',
			'name' => 'Trinidad and Tobago',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Port_of_Spain',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TN',
			'name' => 'Tunisia',
			'continent' => 'Africa',
			'offset' => '1',
			'TimeZoneId' => 'Africa/Tunis',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'TR',
			'name' => 'Turkey',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Europe/Istanbul',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'TM',
			'name' => 'Turkmenistan',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Asia/Ashgabat',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'TV',
			'name' => 'Tuvalu',
			'continent' => 'Oceania',
			'offset' => '12',
			'TimeZoneId' => 'Pacific/Funafuti',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'UG',
			'name' => 'Uganda',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Kampala',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'UA',
			'name' => 'Ukraine',
			'continent' => 'Europe',
			'offset' => '2',
			'TimeZoneId' => 'Europe/Kiev',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'AE',
			'name' => 'United Arab Emirates',
			'continent' => 'Asia',
			'offset' => '4',
			'TimeZoneId' => 'Asia/Dubai',
			'tier' => '2',
		  ],
		  [
			'country_code' => 'GB',
			'name' => 'United Kingdom',
			'continent' => 'Europe',
			'offset' => '0',
			'TimeZoneId' => 'Europe/London',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'US',
			'name' => 'United States of America',
			'continent' => 'Americas',
			'offset' => '-8',
			'TimeZoneId' => 'America/Los_Angeles',
			'tier' => '1',
		  ],
		  [
			'country_code' => 'UY',
			'name' => 'Uruguay',
			'continent' => 'Americas',
			'offset' => '-3',
			'TimeZoneId' => 'America/Montevideo',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'UZ',
			'name' => 'Uzbekistan',
			'continent' => 'Asia',
			'offset' => '5',
			'TimeZoneId' => 'Asia/Tashkent',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'VU',
			'name' => 'Vanuatu',
			'continent' => 'Oceania',
			'offset' => '11',
			'TimeZoneId' => 'Pacific/Efate',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'VA',
			'name' => 'Vatican City',
			'continent' => 'Europe',
			'offset' => '1',
			'TimeZoneId' => 'Europe/Vatican',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'VE',
			'name' => 'Venezuela',
			'continent' => 'Americas',
			'offset' => '-4',
			'TimeZoneId' => 'America/Caracas',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'VN',
			'name' => 'Vietnam',
			'continent' => 'Asia',
			'offset' => '7',
			'TimeZoneId' => 'Asia/Ho_Chi_Minh',
			'tier' => '3',
		  ],
		  [
			'country_code' => 'YE',
			'name' => 'Yemen',
			'continent' => 'Asia',
			'offset' => '3',
			'TimeZoneId' => 'Asia/Aden',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ZM',
			'name' => 'Zambia',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Lusaka',
			'tier' => '4',
		  ],
		  [
			'country_code' => 'ZNB',
			'name' => 'Zanzibar',
			'continent' => 'Africa',
			'offset' => '3',
			'TimeZoneId' => 'Africa/Dar_es_Salaam',
			'tier' => '5',
		  ],
		  [
			'country_code' => 'ZW',
			'name' => 'Zimbabwe',
			'continent' => 'Africa',
			'offset' => '2',
			'TimeZoneId' => 'Africa/Harare',
			'tier' => '4',
		  ],
		  ];

        foreach ($data as $v) {
            XCountries::create($v);
        }
    }
}
